### ISSUE TITLE
IDE scope should change settings when changing mode

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#107]
FFT/dB:
amplitude: 70
offset: 69

FFT/normalized:
amplitude: 1
offset: -0.005

Time-domain:
amplitude: 1
offset: 0

The offset in the FFT allows the user to see within the window the peak value generated by a sinewave of amplitude 1 centered in an FFT bin. If they were set to 70 and 0 respectively, then the user may be left wondering whether the trace "continues" outside the window or stops at the edge.
These are defaults, the user can change these values, so when the user switches mode, current settings should stashed (in the browser)  and recovered later when switching back.

**Comment by LBDonovan** [comment]
So I had a go at this, the settings change when you switch modes, but at the moment the old settings aren't stashed because it is quite a hassle to do that.

I renamed amplitude to attenuation, because that seems to make a lot more sense for the time-domain and normalised FFT. It means that for both of them, attenuation of 1 and offset of 0 are the 'neutral' values. I'm not sure about the decibels settings though (even though the decibel axis plot looks way better now!) because the 'neutral' settings are 70 and 69, which is not intuitive. Do you have any ideas how this could be improved?

Also, the decibel axis option adds about 10% cpu usage vs the normalised axis option. Is that expected?

**Comment by giuliomoro** [comment]
Cannot reproduce the thing about 10% CPU usage, where do you see the increase? in `/proc/xenomai/stat`, in top `scope` or in top `node` ?

**Comment by giuliomoro** [comment]
I am pretty happy with the "neutral" settings now.
In order to make them clearer, I would suggest adding proper labelling to the Y axis.
Made a better name for amplitude/attenuation is "range"? 

CPU usage is overall high, but not sure we can do much about it, except bypass node and create a websocket between the scope window in the browser and the Bela program.
We could also think of using `log10f_neon` for this application, where approximations are well tolerated.

**Comment by LBDonovan** [comment]
To reproduce, on scope-dev run the scope-sliders example, and switch between normalised and decibel y-axis. scopeTriggerTask sees a ~11% increase.

**Comment by giuliomoro** [comment]
Confirmed. Also, changing the X axis to logarithmic increases CPU usage by about 5%.
