### ISSUE TITLE
IDE multiple windows conflicts

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#153]
I cannot seem to be able to have multiple windows open with different files.

**Comment by giuliomoro** [comment]
Ultimately I ended up with the `main.cpp` file having this content:
`This file has been edited in another window. Reopen the file to continue`

as in : this is the content that has been written to disk, overwriting the original file content !!

**Comment by LBDonovan** [comment]
Yeah, being able to edit in multiple tabs is the biggest source of bugs in the whole IDE. I'll get on it.

**Comment by giuliomoro** [comment]
If it is not possible to edit in multiple tabs, we should prevent it altogether, in order to avoid any possible data losses like the one above.

**Comment by LBDonovan** [comment]
It's definitely possible, it was working before the merge. It's just quite tricky to make sure losing data can't happen.

**Comment by roberthjack** [comment]
On this subject I wonder how much benefit there is in using additional tabs from the browser as opposed to creating our own tabs at the top of the IDE in one browser window. By default we could even have every file within the project open as an additional tab within the one browser tab. This would surely simplify issues within one project, but I guess it would not remove the problem of overwriting work all together as people will be opening multiple tabs at some point anyway.

As a reference for this see the new Arduino create online editor. They also make the documentation an additional tab which could work quite well for us we could render the Fritzing images too. An alternative to using the side menu, although for sure there are benefits to being able to view both code and documentation at once.

**Comment by LBDonovan** [comment]
Using soft tabs within a single browser tab would be easier to manage but it would take a lot of time to do at this stage, and its not likely to happen any time soon, especially as the browser tabs work already. I think its important we give some attention to using multiple tabs when we do testing so we catch any bugs that might pop up.

I like the idea of better embedded documentation along with fritzing images etc though, I could definitely see putting that in a tab.

**Comment by disastrid** [comment]
I'm all for improving the IDE's UI, but starting a redesign without a serious effort to get user feedback is a path to madness - the IDE functions because so much restraint has been applied to what's there. After the next wave of board sales I would be very interested in getting user feedback to find out how they use the IDE and what their needs are, and design according to that data. Otherwise we run a serious risk of pouring time and effort into implementations that may not serve any real purpose, and making the classic design mistake of thinking that our needs are the needs of all users, or over-featuring because we're trying to solve problems that we don't have any proof actually exist.

—
S. Astrid Bin
http://astridbin.com <http://astridbin.com/>

**Comment by apmcpherson** [comment]
Agreed. Major changes, UI or otherwise, should wait until the next dev cycle, and should reflect user testing and feedback.
