### ISSUE TITLE
Add default support for "vfp fast" in the core code

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#162]
To be called in `Bela_initAudio()`.
This would make the audio thread and any Auxiliary Task use non-IEEE-compliant(denormals flushed to zero) floats, making vfp operations faster in case denormals are generated.
Users would then be able to disable this on a per-thread basis by calling `disable_runfast()`. It is up to the user to make sure they compile their denormal-critical code so that it does not generate NEON instructions (which are non-compliant).

@apmcpherson anything against this?

**Comment by LBDonovan** [comment]
Would this cause unexpected results when you're calculating sensitive and small values like filter coefficients?

**Comment by giuliomoro** [comment]
Well that's possible. Most likely - I'd say - it would cause "unexpected results" when USING an IIR filter, where if your input goes to zero, after having been non-zero, the output may get denormals.
Point is if the compiler was to use NEON, this rounding error would take place anyhow. By forcing this mode of operation we just make sure it ALWAYS happens. If the user is not happy, then the only deterministic way for them to make sure denormals are not flushed to zero is to compile their file with a different flag, like `-mfpu=vfp` AND disable `runfast`.

**Comment by giuliomoro** [comment]
... UNLESS they are using `double`, in which case the compiler will have to generate vfp instructions. You could therefore - by using double - expect a consistent IEEE-754-compliant behaviour on the Cortex-A8 regardless of compiler/compiler settings and enabling `runfast` would disrupt this expectation.

Yet:
a) I do not think denormals are an actual issue in filter coefficients computation
b) I believe most users would benefit from the [faster computation](http://lists.bela.io/pipermail/dev-bela.io/2016/000007.html) while only a small number would be negatively affected by this.

**Comment by apmcpherson** [comment]
I think on balance it's a good idea to enable this by default, as long as there's clear documentation for how to turn it off if it becomes problematic.

I tend to dislike things that could produce non-IEEE754-compliant output, mainly because in porting existing libraries, the output might depend in non-obvious ways on denormals. But as you say we are trying to use NEON as much as possible, where this happens anyway. So the concrete performance benefit outweighs the possible edge cases where it creates problems, again as long as the alternatives are documented somewhere.

When using `double`, with its greater range of exponents, presumably denormals in that situation are going to be incredibly small such that they wouldn't make any difference to audio, even within an IIR filter.

**Comment by giuliomoro** [comment]
ok.
https://github.com/BelaPlatform/Bela/wiki/IEEE-754-floating-point-on-Bela
