### ISSUE TITLE
Example: sinetone_optimized 

### ISSUE THREAD

**Issue by roberthjack** [BelaPlatform/Bela#170]
Should perhaps be more than a single frequency played by 120 oscillators, oscillator bank?

**Comment by roberthjack** [comment]
Added example to dev of oscillator bank into basic examples though should probably go elsewhere. Random frequency and amplitude modulation. @giuliomoro please check there are no criminal inefficiencies.

**Comment by giuliomoro** [comment]
Very nice example.
Can you make it stereo ?

Some remarks:

- we should replace all the instances of the likes of 
```
			if(gPhases[k] > 2.0 * M_PI)
				gPhases[k] -= 2.0 * M_PI;
```
with 
```
			if(gPhases[k] > M_PI)
				gPhases[k] -= 2.0 * M_PI;
```
because approximated version of sinf are more likely to work nicely in the `-M_PI,M_PI` range.
- there are two ways of doing things more efficiently than this.
One is [`sinfv_c` / `sinfv_neon`](http://192.168.7.2/Documentation/math__neon_8h.html#a1d6a154aac95df2c81c6b5ef8f625005), which computes the sine of an array of phases. This is at least3X faster than the code you wrote.
The other one is the current oscillator-bank example, which is even faster.
I am not sure if we should provide example for each of them or create a blog article about "incrementally make the best oscillator bank". Thoughts?

**Comment by apmcpherson** [comment]
A blog article about progressively more efficient oscillator banks would be great. Probably something like: sin(), sinf(), various approximations, wavetables, `sinfv_neon`, then the oscillator_bank example in hand-tuned assembly.

**Comment by giuliomoro** [comment]
it's sort of a shame that the oscillator_bank example turns out to be both
a) the most efficient and b) the most flexible (as it is wavetable-based).

**Comment by LBDonovan** [comment]
While a blog article about this would be cool, I think an API wrapper around the assembly-tuned oscillator bank would be more useful!

**Comment by giuliomoro** [comment]
@LBDonovan that goes without saying!
