### ISSUE TITLE
Over-expensive audio code can hang the board

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#189]
Running the `vangelisiser` example from the IDE (despite its warning to use Heavy) will hang the board: Bela program running, but no way to stop it. Surprisingly, the cape button also fails to stop it.

I experienced this problem before when overloading the oscillator bank, but only when using `BELA_USE_XENOMAI_INTERRUPTS` in PRU.cpp. It's possible that this comes from a change in the `sleepTime` code in PRU.cpp, or that there is something in the libpd code that behaves differently. It needs further attention.

One question is whether the cape "click" action should be moved into the Bela program at Xenomai priority, so we can guarantee the ability to stop the program, even if all of Linux has become unresponsive.

**Comment by giuliomoro** [comment]
Confirmed.
`sleepTime` is still the same as it used to be.

I have had this issue in the past, I think it happens when the time it takes for `render()` to run is larger than a blocksize and just about smaller than a multiple of `sleepTime`.

The button should be checked from within the Bela program, as requested here: https://github.com/BelaPlatform/Bela/issues/175
We could probably have the Bela program detecting short presses and the other script waiting for long button presses to trigger a graceful shutdown.

**Comment by giuliomoro** [comment]
Alright so I pushed it here https://github.com/BelaPlatform/Bela/commit/955299135ad0867be9e963afe926ed6ba1303e56
and here https://github.com/BelaPlatform/Bela/commit/96c28773125af5eea838ec6487b6caa1ad044724

Whether we want to ship it today is a separate topic.
