### ISSUE TITLE
PRU: DAC_CS_ASSERT is perhaps useless?

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#220]
The pinmuxer actually exports P9_17 as "0x10" (spi0_cs0), but this pin is handled through the PRU and CPP code as if it was exported as "0x27" (GPIO0:5).

The net result is that the thing still work (maybe it is asserted by the SPI controller itself?), but it may lead to misleading conclusions (say that someone is working on the PRU code and tries to write to that pin through the GPIO registers: they may end up wasting an entire Saturday afternoon ).

**Comment by apmcpherson** [comment]
This might be the same issue that is preventing the BBGW from working. Good catch! I do know that the pin toggles properly on the BBB, which must be because mode 0 is spi0_cs0, so in fact this is being handled directly by SPI as you say.

Check the device tree overlay for SPI0, assuming it's loaded, to see if it is responsible for setting this pin to mode 0.

**Comment by giuliomoro** [comment]
It is set by the BB-SPIDEV0 dtbo.
If I set it to 0x27 (GPIO0:5), it still works fine.

Not sure how this would influence the behaviour on the BBGW. I tried 0x27 on the BBGW and it does not change the final result: noise noise noise

**Comment by giuliomoro** [comment]
Note that this actually is the CS for the DAC (which is on SPI0), not for the ADC (which is on SPI1) as I had incorrectly stated in the beginning.

**Comment by giuliomoro** [comment]
Fixed by new, comprehensive, dtbo.
