### ISSUE TITLE
scopeSendBufferTask and OSCReceiveTask cause mode switches even if the scope window is closed

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#23]
These mode switches are in the respective threads and NOT in the audio thread, so they are not critical, yet they should not be there (as they waste some resources).

Ideally once a thread that uses secondary-mode (kernel-mode) functions, it should stay in secondary mode without jumping back and forth between modes. 

Note: using `Bela_scheduleAuxiliaryTask` will surely cause a mode switch to primary mode.

**Comment by LBDonovan** [comment]
@giuliomoro so why is this happening?

Only two lines of code are run during Scope::sendBufferTask, one is a pointer dereference, which should not cause any problems, the other is a call to UdpServer::send which presumably causes the mode switch.

I can easily prevent the mode switch when the scope window is disconnected by simply bypassing the UdpServer::send call, but when the window is connected, the mode switches are still going to happen.

Is it possible to force the task to run in secondary mode by default, as we know that it's going to have to switch to secondary anyway? Or there some other way of keeping the task in secondary mode, by sleeping and resuming it rather than scheduling it?

**Comment by giuliomoro** [comment]
iirc `Scope::sendBufferTask` is scheduled with Bela_scheduleAuxiliaryTask, right? This is a xenomai mode-only function, I believe, so it causes a mode switch to primary mode and then `UdpServer::send` switches it to secondary mode.
Usually if you have tasks that require secondary mode, you would run them in something like
`while(!gShouldStop) { <yoursecondarymodething>; usleep(1000) }`, so it does not require to be re-scheduled and it stays in secondary moment the whole time.

If this solution is not viable in this case, then I guess bypassing the `UdpServer::send` when inactive is good enough: when the scope is active, performance should not be a concern, but we want to make sure that an inactive Scope does not interfere with the program's performance.
