### ISSUE TITLE
IDE: symlinks to folders are not considered folders

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#568]
... which means that a `project` folder symlinked to something else will not be recognized as an existing project. See here https://forum.bela.io/d/1020-new-ide-gui-and-shareable-libraries/4

**Comment by roberthjack** [comment]
Regarding the radio buttons missing for the cape settings, we encountered
this at the BBC workshop where someone was using Firefox.

The problem is that the radio buttons are actually positioned 1000px or so
to the right of the side bar menu off screen. We were able to adjust them
by playing around with inspector and zoom.

**Comment by giuliomoro** [comment]
@roberthjack see [here](https://github.com/BelaPlatform/Bela-private/issues/226)
