### ISSUE TITLE
IDE: pgrep when running project

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#69]
When a project contains an `.scd` file it is now run with SuperCollider (using the system-wide `sclang` executable).

For a project called `123`, which contains an `.scd` file and is thus run with `sclang`, I get this error message in the IDE console:
```
{ Error: Command failed: pgrep 123

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5) killed: false, code: 1, signal: null, cmd: 'pgrep 123' }
```

There must be some `pgrep`ping taking place,
* what is the reason for this?, and
* how do we avoid it ?

**Comment by LBDonovan** [comment]
You should only see that error message sometimes, and only once when it appears, is that right?

In order to track the linux process cpu usage, I run pgrep to get its pid. It usually only runs once, but occasionally it seems to fail and so then has to be run again after a short delay. As long as you don't see an uncaught exception in the console, it actually means node is handling the error, it's just I'm (unnecessarily) printing the error to the console when it happens.

**Comment by LBDonovan** [comment]
Actually, there was a weird bug associated with this, which is that the linux process name gets cut-off at 15 chars in length. Try running an example project and checking top, and it will name the process as 'exampleTempProj'. Not a big deal, but not expected either.
