### ISSUE TITLE
IDE: scope should trigger considering interpolated value

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#75]
So that if you have a trigger at 0 and two successive samples `x0=n` and `x1=n+1` are y(x0)= -0.001 and y(x1) = 0.003, the image should be centered around `x=n+0.25`. This should make the image more stable.
This assumes the oversampling takes place in the browser

**Comment by LBDonovan** [comment]
@giuliomoro so at the moment the oversampling and triggering takes place on the board. The triggering (which determines where the image is centred) has to take place on the board for efficiency, so in order to do this the oversampling and interpolation would have to be done on the board too.

What would be the advantage to doing the oversampling in the browser? The cost of doing this on the board must be pretty low.

Are you sure oversampling is the source of the instability? Because the image still seems to be slightly unstable at 100% zoom, i.e one sample per pixel and no oversampling. Oversampling exaggerates it, but I don't think it's the root cause. It would be nice to get rid of the instability though...

**Comment by giuliomoro** [comment]
I am fairly sure the instability is due to the fact that almost never you have `y[n] == triggerLevel`.
You would not need to do the whole oversampling thing on the board, only when you detect a trigger, linearly interpolate between the neighbouring two samples to find the fractional index at which the signal actually crossed the threshold.

I see that the IDE loads increases a lot when zooming in the scope, I think this oversampling taking place on the board is the cause for this, am I wrong?

**Comment by LBDonovan** [comment]
The increased load could be the oversampling, or it could be because triggering happens more often when you're zoomed in.

I'll have a look into it.

**Comment by giuliomoro** [comment]
If the issue is that it triggers more often, then I guess  it would make sense to limit the maximum number of triggers per second to something reasonable, e.g.: 30 or something (make sure that the single trigger will still work).
