### ISSUE TITLE
WriteFile should support non-float values, and needs documentation

### ISSUE THREAD

**Issue by apmcpherson** [BelaPlatform/Bela#96]
From a Bela user, after I asked 'Have you tried `setFormat()` using `%d` instead of `%f`?':

> Doesn't work. file.log() insists on a float argument, and simply transfers it to a vector of floats.
> The background process then extracts these and writes them to the output file, either as 4-bit binary writes, or using the format with fprintf().

In general it would be useful to support different data types with WriteFile, and also make it clearer how to use different formats. WriteFile should also get some Doxygen docs.

**Comment by giuliomoro** [comment]
Most docs is already in place [here](http://docs.bela.io/logging-sensors_2render_8cpp-example.html) and [here](http://docs.bela.io/classWriteFile.html#a56314568f2264507f2e6e9f1b67a9c33), though a) it is pretty recent, and b) could use some improvements (in particular the former's formatting is a bit messed up because of an old version of doxygen but looks nice on the board).

Not sure what the interface should look like to accept ints. Maybe just accept `void*` ?

Right now, you could probably pass them when writing binary file: `writeFile.log((float*)myInt32Pointer, size)`, but surely it is not very convenient.
Note that the format is mostly ignored when logging binary files: it is only used for echoing to the console.

**Comment by Bill-3d** [comment]
I've made a trivial mod to the WriteFile.cpp (and WriteFile.h), renaming them to WriteIntFile.*.
That expects int's instead of floats, just replace float with int wherever it occurs. I expect that
using %d rather than %f should work, but I've not tried it as I am using binary files.

Making it more general would be nice, but it would then need a tag with each value to indicate what type it was. Given the sort of usages that are envisaged, it's probably not worth the effort or the overheads.

**Comment by giuliomoro** [comment]
Merged in https://github.com/BelaPlatform/Bela/issues/246
